### PR TITLE
Multi export texture folder definition

### PR DESCRIPTION
**Pull request by elpie89**
Added the possibility to define different textures folder for each ExportItem in the multiFileExporter menu

### CODE REVIEW

**Comment by Drigax** [comment]
Since this contains  changes on top of #583, it would probably be best to review this after that is checked in.

**Comment by elpie89** [comment]
i'l merge the master in here tomorrow morning

**Comment by Drigax** [comment]
Thanks, your changes look good!

**Comment by elpie89** [comment]
As I was working on path features I took the time to polish the format path utilities
Our artists were asking for a better FolderBrowser, the default one of WinForms is really bad, I added the Microsoft.WindowsAPICodePack to the project to use an enounced folder browser

Also, the old way to distinguish the relative paths and the absolute paths weren't clear
I replaced with a system that use colors to give feedback

so this :
`[project folder]relativePathToGltf` 
is now just an absolute path formatted with two different colors

This way the entire format unformat logic is easier and I removed some unused methods
I think this is enough for this PR

**Comment by Drigax** [comment]
@elpie89 I believe [your latest change to this PR](https://github.com/BabylonJS/Exporters/pull/584/commits/dbe0444edae1b64722f2c375a350f0202d7047c7) caused a regression (#587).

To quickly unblock our users, I'll need to revert this specific commit. Please create a new PR with the commit so we can figure out why this is breaking our installation.

**Comment by Drigax** [comment]
Sorry, I was wrong to revert this change. It turns out this was caused by the reference added to ManagedServices.dll via #580. I was able to fix our installer, and will revert my reversion shortly.

**Pull request merged**
