### PR TITLE
Fix issues and update dlls

### PR DESCRIPTION
**Pull request by noalak**
Fix issue #76 
Fix issue #49 
Update dlls including last @Selmar updates

### CODE REVIEW

**Comment by Selmar** [comment]
Just curious, what's the rationale behind setting OPAQUE explicitly instead of leaving it out?

**Comment by deltakosh** [comment]
I wanted it to make sure all engines will have it explicitely and because some artists were complaining about not finding it in the file

**Comment by Selmar** [comment]
I doubt any engine would "forget" to set a default to opaque, but I can see why an artist would be worried. 👍

**Comment by deltakosh** [comment]
And artists are respectful people I don't want to mess with :)

**Pull request merged**
