### PR TITLE
Support Hair and Fur 3dsmax modifier

### PR DESCRIPTION
**Pull request by kutomer**
#51

### CODE REVIEW

**Comment by noalak** [comment]
Thoughts:
1) Good stuff!

2) Verions 2015 & 2018 raise an error because you encountered a technical issue for those versions or you just ignored/couldn't test them?

3) I don't really see why a for loop (or 2) would be required. just pick what you need directly:
`var paramBlock = modifier.GetParamBlock(0);
spacing = (int)Math.Round(paramBlock.GetFloat(XXXX, 0, 0) / 3); // Cut length`
In case i'm wrong, in the paramBlock switch, could you replace the name of each parameter by its actual paramId so it is not language sensitive.

4) I'm surprised you don't have a warning raised everytime as i would have expected the tip color to never be null (pale brown by default) line 74. But if it works...Nevertheless good idea for the warning messages keep them even if you remove the for loop!

**Comment by kutomer** [comment]
@noalak 
1. Thanks.

2. 
2015 - doesn't support Hair and Fur modifier at all.
2018 - I couldn't check it, I'm using Mac, our modeler have 3dsmax 2017 installed, so I didn't want to just guess, sorry for that.

3. will do.

4. I also thought that this warning will be raised every time :)

furthermore, I've changed the parameters a little bit so the exported Babylon mesh will be closer to what you see in 3dsmax.
That's a bit confusing but I think that it will be better to use the root thickness to determine the density (and not the density) that's because density in Babylon works in a way that the lower the density there are fewer hairs and each is therefore thicker.

I'm fixing it now and will push it within the next few hours.

Thanks again :)

**Comment by kutomer** [comment]
done @noalak

**Comment by noalak** [comment]
Perfect!
Will test with 2018 and 2017 French versions tomorrow.
Can you share a sample max file ? or add it directly to this PR as you wish.

**Comment by kutomer** [comment]
Thanks :)
attached sample file.
[sample.zip](https://github.com/BabylonJS/Exporters/files/1721016/sample.zip)

**Comment by noalak** [comment]
I've downloaded your project and the sample file.

Couldn't test the end result as the sandbox doesn't have external reference to FurMaterial.

Anyway tested export process:
1) 3ds max 2017: The tip color warning is displayed everytime. Export is fine though. If you find a workaround to keep the warning message but to only print it when necessary it would be really nice. Otherwise, just remove it and it will be added to the documentation.
2) 3ds max 2017 French version: modifier is not recognized. Would be nice to find a solid fix to share your work with wilder range of users at some point. For now you can add an extra condition `|| modifier.Name == "Chevelure et Pelage"`
3) 3ds max 2018: all right!

Quick fix 1) & 2) and good to go for me!

Congratz and thanks for your work :)

**Comment by deltakosh** [comment]
@noalak feel free to add a reference to mat libs in the sandbox

**Comment by deltakosh** [comment]
I've just added reference to mat library in sandbox so you should be able to test :)

**Comment by kutomer** [comment]
@noalak done.
Thanks :)

**Comment by noalak** [comment]
Here are the results for the sample file provided by kutomer.

By default, it's very dark. Any reason for that @kutomer @deltakosh ?
default

With higher light intensity:
withhigherlightintensity

We can see the gap between the fur created from the side and the one created from the top. I've no idea on what we should have, so I let you comment on it @deltakosh 

Babylon file: [cylinder_rose-blue-flower-rose-blooms.zip](https://github.com/BabylonJS/Exporters/files/1726774/cylinder_rose-blue-flower-rose-blooms.zip)

**Comment by kutomer** [comment]
@noalak , I don't see it's too dark. (in my application, I don't have light with high intensity)
Maybe it's the black furColor?

**Comment by deltakosh** [comment]
Adding @luaacro for comments on fur rendering

**Comment by julien-moreau** [comment]
Hey sorry for the delay!
Is it rendered with the property "furColor" equals to new Color3(1, 1, 1); ?

**Comment by noalak** [comment]
You can access fur material properties in the babylon file provided in the zip (beautify it [here](https://codebeautify.org/jsonviewer)).

furColor is (0, 0.4549, 0.6039). Setting it to (1,1,1) make it brighter but still darker than i would expect (need to increase light intensity).

**Comment by kutomer** [comment]
Any news? :)

**Comment by julien-moreau** [comment]
Sorry for the delay, I need to investigate for sure because I have no idea for now :(
Anyway, I focus 100% on the problem tomorrow until I find the solution!

**Comment by julien-moreau** [comment]
Hey just reproduced, it looked like the normals were badly computed in the shader
Fixing it right now :)

**Comment by julien-moreau** [comment]
Pull Request created https://github.com/BabylonJS/Babylon.js/pull/3851

**Comment by kutomer** [comment]
@julien-moreau Thanks a lot :)
@noalak Are we good now?

**Comment by noalak** [comment]
@julien-moreau 
Using the babylon file _cylinder_rose-blue-flower-rose-blooms.zip_ linked previously i don't see any difference light-wise. Is that normal?
The fix applied to normal is about the last sample file given by kutomer (carpet)?

**Comment by kutomer** [comment]
It didn't work for me as well...

**Comment by kutomer** [comment]
@julien-moreau Just checking in, but... any news?

**Comment by julien-moreau** [comment]
Dam! Just saw your friendly reminders!
Checking ASAP, so sorry !

**Comment by kutomer** [comment]
@julien-moreau nothing to be sorry for, your help is very much appreciated :)

**Comment by deltakosh** [comment]
Any news?

**Comment by julien-moreau** [comment]
image
According to this screenshot, black ambient occlusion color is the wanted behavior, to help the eye seeing the "thicker" or "reflief", like "depth

**Comment by julien-moreau** [comment]
If disabled, this will render: 
image

**Comment by kutomer** [comment]
@julien-moreau just want to make sure that I understand - the occlusion color is black (can I control this color somehow?) so when I specify "furColor" (or texture) the actual fur color will be from that shade to black? (but mostly this color)

The problem is that this behavior makes the hair look much darker than expected (in the specified example above a completely white fur looks gray)

If I understood it correctly I think a better solution will be to support something like "hair base color \ texture" (same as 3dsmax Hair & Fur modifier)
* the hair "lower" parts will be in the "base color" and the higher in "tip color" I think that's a better solution for hair perspective.

if the above solution is too complicated I think the second option (disabled occlusion color - completely white) will be more predictable and it will be up to user to create a fur texture that looks realistic. 

What do you guys think?

**Comment by julien-moreau** [comment]
I'm adding the "furOcclusion" property to control the occlusion strength: https://github.com/BabylonJS/Babylon.js/pull/4235

I took a moment to read about fur rendering and it looks like most realistic fur renderers do not use the method we have now. They mainly use a combination of complex shaders including geometry shaders :(

**Comment by kutomer** [comment]
@julien-moreau awesome thanks!
@noalak So... are we good to go?

**Comment by julien-moreau** [comment]
Have you tested to let me know if it fits your request ? :)
Thanks!

**Comment by kutomer** [comment]
@julien-moreau sorry for the late response again - but on which scale does the `furOcclusion`? I've tried few possible numbers (0, 1...) all seem the same to me.
Am I missing something here?

**Comment by julien-moreau** [comment]
Can you go over the interval [0, 1] and test with value 2 for example?

**Comment by kutomer** [comment]
Yeah sure, it's the same model I've uploaded on Feb 27.
With 0,1,2 furOcclusion: 

screen shot 2018-05-13 at 11 09 26
screen shot 2018-05-13 at 11 08 24
screen shot 2018-05-13 at 11 07 43

**Comment by kutomer** [comment]
all look exactly the same to me, the image is a bit bigger that's all.

**Comment by deltakosh** [comment]
So we can merge? :) (we need to fix conflicts)

**Pull request merged**
