### PR TITLE
3ds max 2025 support

### PR DESCRIPTION
**Pull request by FrogsInSpace**
adds support for 3ds Max 2025
including new menumanager API support ( plus menu refresh workarrounds )

### CODE REVIEW

**Comment by SergioRZMasson** [comment]
I will take a look, should be done reviewing it today.

**Comment by SergioRZMasson** [comment]
> Thanks, i'll fix the tabs of course i assumed this to be configured via attributes ...

In visual studio go to: Tools->Options->Text Editor->All Languages->Tabs

Change Tab to use "Insert Spaces" instead of "Keep Tabs".

**Comment by SergioRZMasson** [comment]
> Thanks, i'll fix the tabs of course i assumed this to be configured via attributes ...

Sorry, I thought you were asking how to do it in Visual Studio. I'm not sure this can be configured via attributes, though...

**Comment by FrogsInSpace** [comment]
> Sorry, I thought you were asking how to do it in Visual Studio. I'm not sure this can be configured via attributes, though...
no prob, 
AFAIK it can be done via [attributes](https://stackoverflow.com/questions/2316677/can-git-automatically-switch-between-spaces-and-tabs) or even better via .editorconfig

I usually work with a multitude of projects from a a broad range of tech stacks and conventions. so changing the Visual Studio tab settings itself would be not feasable 

I'll create a local .editorconfig, and maybe even create a PR for it later ...

**Comment by FrogsInSpace** [comment]
Tabs have been converted back to spaces
I noticed the existing formatting style mix of "if(..." and "if (..." was unified to "if (..." in the files i touched ( most likely by the untabify extension i used ). IMHO thatsd an improvement in any case at least ...

**Review by SergioRZMasson — APPROVED** [review]
Looks good!

**Comment by FrogsInSpace** [comment]
Thanks for merging, seems the pipeline did'nt build or include the 3dsMax 2025 build in the release assets. Installer says it can't find the Max_2025.zip either 
So i guess this has to be something done somewhere in the CI/CD scripts

**Comment by SergioRZMasson** [comment]
Yep, you are right. I will take a look at the CI.

**Comment by den-dc** [comment]
please i reaaly need 2025 support )

**Comment by SergioRZMasson** [comment]
Done! Can you guys give it a try?

**Comment by FrogsInSpace** [comment]
Installer seems to be working, download the zip and installing but for me the Max 2025 version does'nt load. Not sure about the reason currently.

There is the UiViewmodell.dll included in the Max_2025.zip package which shouldn't be in there ( its a 3ds Max binary ). 
This is due to ref setting copy option not being set correctrly in the project settings
#https://github.com/FrogsInSpace/babylonjs-Exporters/commit/0065160d510e00a5a5a7576f7c6418e30357a3eb

**Comment by FrogsInSpace** [comment]
Okay: appears the the tabs to space commit broke the Babylon menu registration 
( #[tabs to space ](https://github.com/BabylonJS/Exporters/pull/1121/commits/d1a94df76163a610307c33e546a716a2bfe5a0ed)

not sure what it is , but will have a look at it tomorrow ( its already late here :) )

**Comment by SergioRZMasson** [comment]
I'm doing a quick PR to fix the unnecessary copy of 3DS Max binaries

**Comment by FrogsInSpace** [comment]
I got thre reason for the failing menu creation:
For some reason the changed files in the tabs-to-spaces commit are UTEF8-BOM encoded, and running the embedded maxscript fails because of that, i can fix that tomorrow

**Pull request merged**
