### PR TITLE
Implement 3DS Max double-sided materials

### PR DESCRIPTION
**Pull request by jdwilder-google**
This change adds support for double-sided materials in 3DS Max via the 'Double Sided' material.

Split from #510 

It handles 'Double Sided' materials setup like so:
image

### CODE REVIEW

**Comment by Drigax** [comment]
Thanks for splitting the PRs. Would you be able to upload a simple test scene to this comment thread that i can use to validate this?

**Comment by jdwilder-google** [comment]
Of course. Here's the test I used with a simple untextured cube.

[dsmaterial_3dsmax_cube.zip](https://github.com/BabylonJS/Exporters/files/3192624/dsmaterial_3dsmax_cube.zip)

**Comment by Drigax** [comment]
Thanks! Works great. I'll merge it in.

**Comment by EugenioMiolo** [comment]
Hi There!

This is not working for me. See the screenshot, it says Double-Sided material is not supported. I'm struggling to get double-sided physical materials with babylon.

image

Thanks a lot,
Eugenio

**Pull request merged**
