### PR TITLE
Multi-file export (#368)

### PR DESCRIPTION
**Pull request by Selmar**
Implementing #368

This pull request is not necessarily meant to be integrated right away; rather, it is to track and get some feedback on the current state and whether it aligns with your views.

Implemented multi-file export:
- Reset translation of the node used as a scene root.
- Take export settings (file type, etc.) from the exporter window.
- Button to execute multi-file export, with shift-click to modify multi-file export settings: 

image
image

**Issues**:
- Have not tested anything but Max 2016 as I don't have the other versions.
- Have only tested `gltf` format.
- We'll be testing this in-house next week (I will be absent until Thursday 22nov).
- The multi-file export dialog is a modal dialog; this means it blocks interaction with the exporter window. However, this also means it blocks interaction with the 3dsmax window. But, when you click on 3dsmax when the exporter window is not in focus, the exporter window does not show up or become highlighted. It makes it look like 3dsmax is unresponsive. I believe this is due to the exporter window not being a child window of the 3dsmax window (perhaps there was a reason?). We can try changing that, or fix the problem another way.
- Currently, we can not export skins with bones outside of the root node's hierarchy. However, this may be something very useful to have, at least in our case, for example when exporting model LODs that have a shared (animated) hierarchy, or separate characters, etcetera. An alternative (and perhaps better) way to get this to work can be to allow the user to specify layers or selection sets for the file export (in addition to the node?). That way, the different exports can be mixed together in the hierarchy: 
- image

### CODE REVIEW

**Comment by sebavan** [comment]
@Selmar , our top exporter guyz are off for the week so the review will happen will happen probably next week. Do not worry if there is a bit of delay :-)

**Comment by Selmar** [comment]
So far this seems to be working well for us. 

Next week I will add a feature to be able to change many file paths at once.

**Comment by kcoley** [comment]
@Selmar nice work!

**Comment by kcoley** [comment]
@Selmar can you add some documentation for this ?
https://github.com/BabylonJS/Documentation

**Comment by Selmar** [comment]
@kcoley I'll see when I can find some time for the documentation, but it won't be very soon.

**Pull request merged**
