### PR TITLE
Master

### PR DESCRIPTION
**Pull request by MackeyK24**
Current version of babylon.js alpha has issues making clones. This is
version before current that works.

### CODE REVIEW

**Comment by deltakosh** [comment]
What?? Can you repro the issue?

**Comment by deltakosh** [comment]
Please do not patch with hack. We need to fix bugs and not work around them :)

**Comment by MackeyK24** [comment]
Is this meant for me ?

**Comment by deltakosh** [comment]
Yes :) please let me know what the issue is so we can fix the engine

**Comment by MackeyK24** [comment]
I made a copy of the space shooter demo and just update the current
babylon.js...

It gets this error... Dont know why: babylon.js: WebGL: INVALID_VALUE:
uniformBlockBinding: invalid uniform block index
so its gotta be somehting in the the shader/material pileline.

Note: every thing expect the Background and the laser bolts are standard
materials... the background and laser bolt are a custom amiga material.

try the game yourself with the current babylon.js file

http://mackey.cloud/games/tester

**Comment by MackeyK24** [comment]
Not a hack, just going back to a working version until we figure whats
changed in the current babylon.js preview release :)

**Comment by deltakosh** [comment]
Sounds good. We are moving to beta stage soon

________________________________

**Pull request merged**
