### PR TITLE
Implement 3DS Max double-sided materials, and some minor build fixes.

### PR DESCRIPTION
**Pull request by jdwilder-google**
This change adds support for double-sided materials in 3DS Max via the 'Double Sided' material. It also includes some minor fixes for build errors I encountered compiling in VS 2015.

### CODE REVIEW

**Comment by Drigax** [comment]
Thanks for the contribution! I'll give this a closer look next week, in the meantime, can you please separate the double-sided material implementation from the build system fixes?

**Comment by jdwilder-google** [comment]
I'm happy to, but this is the first time I've used github so I'm not sure how.  Is there a way to split up commits in my fork to individual pull requests?

**Comment by Drigax** [comment]
I think you can easiest do this by making separate branches on your fork, and cherrypicking the build system commit to that other branch, opening a PR for it, and then removing that change from this current branch

**Comment by Drigax** [comment]
@jdwilder-google Uhoh, I think we lost the double-sided materials changes via 5f89cc4, can you revert that reversion? ;)

**Comment by Drigax** [comment]
Ah, nevermind, I'll close this PR.

**Comment by jdwilder-google** [comment]
Closing this pull request. I split this into two separate pull requests: #513 and #514.

**Pull request closed without merging**
