### PR TITLE
[3DS Max] Shell material

### PR DESCRIPTION
**Pull request by rlouvat**
The Shell material is a container for other materials and it also controls which material is used in which rendering.

The Shell material contains two materials: "Original Material" and "Baked Material". Following the discussion in #296, only the "Baked Material" is needed for the export.

---

Add the Shell material support for Babylon and glTF export:
- the Shell material itself is not exported
- its first material "Original Material" is not exported
- its second second "Baked Material" is exported
- its parameters "Viewport" and "Render" are ignored

### CODE REVIEW

**Comment by echadwick-wayfair** [comment]
Max2Babylon-1.3.4
3ds Max 2018.4

Hmm, has this been implemented? I cannot get this material to export properly. All meshes using this material setup are exported as Dummy nodes. Here's an example to test with.

image

[box_shell-mtl_max2018.zip](https://github.com/BabylonJS/Exporters/files/2519707/box_shell-mtl_max2018.zip)

Thanks for your help with this!

**Comment by echadwick-wayfair** [comment]
In the screenshot above, if I assign either the Shell Material or the DirectX Shader material to the box, the exporter treats the mesh as a dummy. But if I assign the Multi/Sub-Object material (marked with the green checkmark), then it exports properly as a mesh with vertices.

**Comment by deltakosh** [comment]
Pinging @kcoley

**Comment by echadwick-wayfair** [comment]
Also affects support for DirectX Shader material 
https://github.com/BabylonJS/Exporters/pull/318

**Comment by kcoley** [comment]
@echadwick-wayfair I’ll take a look

**Pull request merged**
