### PR TITLE
AnimationGroup multiselection, merge, clean features

### PR DESCRIPTION
**Pull request by elpie89**
added the possibility to merge exported animation group
added multiselection on delete/export 
added clean button to remove empty animation group

### CODE REVIEW

**Comment by deltakosh** [comment]
@drigax: can you validate when you have a chance?

**Comment by Drigax** [comment]
Sure, I'm a bit busy addressing some bugs, but I noticed that the Animation Group Export is missing from the Babylon export menu dropdown, so I can't properly review this. @elpie89 or @Selmar would you be able to help figure out what happened?

**Comment by Selmar** [comment]
It was never in the export menu: right-click on the scene > babylon > babylon animation groups. Not saying we can't add it there, but the right-click menu is where the object properties and scene properties are too.

**Comment by Drigax** [comment]
Ah, right. my mistake :)

**Comment by elpie89** [comment]
@Drigax 
something went wrong here, merge and clean buttons are no longer in Babylon master after the last merge

**Pull request merged**
