### PR TITLE
Installer support for 3ds max 2024/2025

### PR DESCRIPTION
**Pull request by FrogsInSpace**
add Babylonjs Installer support for 3ds Max 2024 and 3ds Max 2025

### CODE REVIEW

**Comment by SergioRZMasson** [comment]
I'm not sure adding 2025 would make sense since we don't currently provide a plugin for that.

**Comment by FrogsInSpace** [comment]
@SergioRZMasson i agree. 
While updating the plugincode for 3ds Max 2025, i ran over a major roadblock due to removed functionality in the 3ds Max NetSDK dealing with actiontables and menuhandling.
After that reoadblock is removed it makes sense then...

**Comment by SergioRZMasson** [comment]
Sure, but I think we can keep the changes that add support for Max 2024, since we do have support for that.

**Comment by FrogsInSpace** [comment]
I solved the roadblock regarding 3ds Max 2025's new menumanager API and created a new PR
https://github.com/BabylonJS/Exporters/pull/1121
the new one also includes the installer update so this one can be closed

**Pull request closed without merging**
