### PR TITLE
3DS Max: Update => from now on Helpers (Dummy) are always exported

### PR DESCRIPTION
**Pull request by rlouvat**
As requested by @Selmar in #161 

@deltakosh is it ok for you ?

### CODE REVIEW

**Comment by Selmar** [comment]
I have a question: the `alreadyExportedNodes` array uses the `name` property, but the `name` is not guaranteed to be unique for a single node, is it? Shouldn't it use the node.id or something like that? @noalak  ?

**Comment by Selmar** [comment]
I also think this does not work with the AnimationGroup tool and has to be revised before we merge that. The animation groups export node/bone animations in a different place. @noalak #197

**Comment by rlouvat** [comment]
Thank you Selmar for your pertinent observation. Instead of the name (I though they were unique), I will use the id.

**Comment by Selmar** [comment]
Another issue: it is exporting helpers that aren't selected if "export only selected" is ticked.

**Comment by rlouvat** [comment]
In this pull request #204 , as suggested the `alreadyExportedNodes` uses the `id` property and the issue is fixed.

**Pull request merged**
