### PR TITLE
#245 - Windows Installer for 3ds Max and Maya exporters. v1.0

### PR DESCRIPTION
**Pull request by Jaskar**
- Log / warn / errors are now colored for a better visibility
- An error is raised if the app is not launched in admin mode
- Buttons for "Update all" et "uninstall all"
- "Update all" bug fix
- Update button greyed if already up to date

### CODE REVIEW

**Comment by sebavan** [comment]
Looks good :-)

@Jaskar could we use that : https://stackoverflow.com/questions/2818179/how-do-i-force-my-net-application-to-run-as-administrator

to ensure the admin mode is set ???

This would be great !!!

**Comment by sebavan** [comment]
Also, would it be possible to rename form1 to mainForm in the sources ?

**Comment by sebavan** [comment]
@Jaskar, it is almost all good just miss 2 things:
* Rename form1 to mainForm
* make the window a bit larger due to high dpi screen overlaps:
image

I ll merge it right after :-)

**Comment by sebavan** [comment]
Also from the latest tests, it looks like the update is not hidden once installed.

**Comment by Jaskar** [comment]
@sebavan 
- Rename form1 to mainForm -> OK
- make the window a bit larger due to high dpi screen overlaps (hours overlaps button) -> Yep, it's ok. I tried to make it as smaller as possible for little screens. (but I'm not a pro to design forms...)
- Also from the latest tests, it looks like the update is not hidden once installed. -> The update button ? It's working here ... It's hidden only if your exporter is up to date

**Comment by sebavan** [comment]
Ok then I will merge and check on the deployed installer :-)

**Comment by Jaskar** [comment]
Woops, I didn't commit before your merge ! I was waiting for your answer first

**Pull request merged**
