### PR TITLE
guid serailization has been moved to user definied properties

### PR DESCRIPTION
**Pull request by elpie89**
the GUIDs dictionary is reinitialized when a container is added and when a scene is opened
for no Node object, the GUID use the appdata chank GUID 
animation group are serialized referencing the GUID instead of the handle
retro-compatibility is granted to files that were using the old serialization system

Some notes.
I cannot test on Max 2016-2017 right now seems like the two notification I added are using a different Delegate signature in older version. I'm not sure on how to handle this

This is jsut a first step to support containers.
The next one will be to move the serialization from the root node to the container itself

### CODE REVIEW

**Comment by elpie89** [comment]
#564

**Comment by elpie89** [comment]
I'm trying to add the compatibility to max 2015-2016-2017
I'm stuck here

```
private void OnNodeAdded(IntPtr objPtr, INotifyInfo infoPtr)
{
                IINode n = (IINode)infoPtr.CallParam; 
}
```

in older version of max is 

` private void OnNodeAdded(IntPtr param0, IntPtr param1)`

I can't find a way to get some info from this signature

Any Idea?

**Comment by sebavan** [comment]
Not for me, let s see if @deltakosh  or @Drigax  might have any ideas ???

Also this will probably need a bit of merging pain after #566 goes in :-( sorry for that.

**Comment by elpie89** [comment]
> I'm trying to add the compatibility to max 2015-2016-2017
> I'm stuck here
> 
> ```
> private void OnNodeAdded(IntPtr objPtr, INotifyInfo infoPtr)
> {
>                 IINode n = (IINode)infoPtr.CallParam; 
> }
> ```
> 
> in older version of max is
> 
> ` private void OnNodeAdded(IntPtr param0, IntPtr param1)`
> 
> I can't find a way to get some info from this signature
> 
> Any Idea?

I found a way finally it's already pushed

**Comment by Drigax** [comment]
Thanks, please merge in master before we can check this in.

**Comment by elpie89** [comment]
should be ok now

**Pull request merged**
